### PR TITLE
Delete docker-pref-macOS.png

### PR DESCRIPTION
**Pull request by ghostdock**
the shadow will be cropped to have an improved consistence to all images in the guides.

### What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

#### Depends On

The main reason is that this screen in visible without the shadow to the reader.

### CODE REVIEW

**Comment by andreassiegel** [comment]
Well, as long as you have a light background, the shadow is visible:
image

And as we already discussed, the shadow is part of the window decoration on macOS, and we therefore shouldn't care about it in my opinion.

Instead of arguing about cropping shadows, we could rather agree on taking all screenshots on macOS and be consistent this way.

Nevertheless, I'm totally fine with having one guide on Ubuntu or any other Linux while another is been written (and _"screenshot"_) on macOS. If someone wants to go crazy, I'm even fine with a guide showing stuff on Windows. I don't care. In fact, it actually shows that the DevKit can be used everywhere.

**Comment by ghostdock** [comment]
I love my macbook! I like macos. What maybe I not would do is to lift one brand over our brand. As a potential customer / decision maker  / sales manager that will evaluate us, I would expect to see quality everywhere even in form of endurance documentation styles. We could do that better.

**Comment by andreassiegel** [comment]
Managers probably don't care about how screen shots look. And developers, that are more interested in screenshots are probably happy to see "their" platform.

Especially since we usually don't have a GUI, and therefore no real need for screenshots, this discussion is more or less pointless. The screenshots we currently have either illustrate Postman or Docker, and especially Postman has no implications regarding SMART COSMOS. SMART COSMOS could run on Linux in AWS, but is accessed using Postman on Windows. Thus, we would have a Windows screenshot for a Linux system. So what?

**Comment by andreassiegel** [comment]
BTW: In the end, this discussion is about a **macOS** screenshot of a **macOS** tool in the configuration instructions for **macOS**... 😐 

This particular thing doesn't even exist in that form elsewhere.

**Comment by sdomula** [comment]
Closed. This file does not live in this repo anymore. Discussion should move to slack.

**Pull request closed without merging**
